### ISSUE TITLE
Table of contents sidebar is too far down the page

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-parent-2021#139] opened 2024-06-07 21:07 UTC
When scrolled to the top of the page, the table of contents sidebar is too far offset.

![Screen Shot 2024-06-07 at 17 00 25](https://github.com/WordPress/wporg-developer/assets/541093/3126c1f0-3c59-45d6-a9e6-fc591d94af1a)

This seems to be new with the Gutenberg update, because constrained blocks now get `position:relative` https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/group/style.scss#L6

I'm not sure if we should unset the position:relative or adjust the top spacing on the sidebar.

**Comment by adamwoodnz** [comment] 2024-06-10 01:30
> This seems to be new with the Gutenberg update, because constrained blocks now get `position:relative` https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/group/style.scss#L6
> 
> I'm not sure if we should unset the position:relative or adjust the top spacing on the sidebar.

Agreed that this is the root cause. Transferring this to Parent where I think we should set the `.has-three-columns` class to `position: relative` so that we have more control over the layout from that parent node. This will require changes in the sidebar container block too, and possibly changes in the consuming themes.

**Comment by ryelle** [comment] 2024-06-12 22:19
@adamwoodnz Is there anything else to wrap up for this issue?

**Comment by adamwoodnz** [comment] 2024-06-12 22:38
Nope, we're done!

**Closed as completed by adamwoodnz** 2024-06-12 22:38 UTC
Labels: [Type] Bug
