### ISSUE TITLE
New Theme: 404 page, links too dark

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-parent-2021#148] opened 2024-07-16 15:46 UTC
## Type of feedback
//dev

## Description
On the 404 page, links offered are barely readable as they have color contrast issues with middle blue on black background. 

## Step-by-step reproduction instructions (optional)
Go to [404 page](https://learn.wordpress.org/lesson-plans/not-found?new-theme=1)

## Screenshots or screen recording (optional)
![Screenshot 2024-07-16 at 17 42 21](https://github.com/user-attachments/assets/da178517-0ef4-4f07-a745-fd3c63b8ce70)

**Comment by adamwoodnz** [comment] 2024-07-16 21:32
I've run an accessibility scan on the page and the links do meet the WCAG 2.1 AA minimum contrast ratio. I'm not sure what other color we would use here. @WordPress/meta-design what are your thoughts please?

Noting that the [standard 404 page](https://wordpress.org/404/) used across much of WordPress.org has the same design.

**Comment by adamwoodnz** [comment] 2024-07-16 21:36
https://webaim.org/resources/contrastchecker/?fcolor=7B90FF&bcolor=23282D

![Image](https://github.com/user-attachments/assets/2a1c4e3b-14a2-4e45-a1c0-e4bae45dbc36)

**Comment by bph** [comment] 2024-07-17 13:45
Despite what computer tools find 'adequate', it's not particular helpful for the lost soul (= the reader who lands on this page) to not get enough consideration to make the choices of alternative pages more prominent, or at least more readable. 

That applies also to the standard 404 pages, even if it were deployed a million times before.

**Comment by fcoveram** [comment] 2024-07-17 16:06
That color is used for text and the focus ring over dark backgrounds across the site. We can definitely revisit the decision, but to keep the style consistent across the site, we would need to revisit most sections to ensure it doesn't clash with other styles already implemented.

**Comment by adamwoodnz** [comment] 2024-08-06 04:07
Transferring to parent theme repo as these styles are not unique to Learn, only the content is different.

**Comment by ryelle** [comment] 2024-12-05 20:30
The link color on dark backgrounds could be updated to blueberry-3 `#c7d1ff` — this has a contrast of 9.9, and while it has less contrast with the surrounding text, the links are underlined so there are no contrast requirements here.

![Image](https://github.com/user-attachments/assets/1029e1e8-d7ba-4cc4-90d7-4a5046e35f41)

See https://github.com/WordPress/wporg-photo-directory/issues/34 where I accidentally thought we already did this 😅 

![Image](https://github.com/user-attachments/assets/af716705-9033-47e2-a646-83c0b72e2337)

**Comment by ndiego** [comment] 2024-12-05 21:29
Sounds good to me.

**Comment by fcoveram** [comment] 2024-12-06 09:07
`blueberry-3` is better for reading, but I don't like the wash effect caused by its low saturation. I wonder if we can revisit `blueberry-3` to keep the same lightness while increasing the saturation. Thoughts @jasmussen?

If I recall correctly, this change involves links, borders, and the focus ring on dark charcoal. Am I missing something else?

**Comment by jasmussen** [comment] 2024-12-06 09:13
Could the links just be white?

I don't have a strong opinion, honestly. I think the original blueberry is plenty legible as-is (though recognize this is a personal taste thing), I also think blueberry 3 can work as is, and I think we can change blueberry 3 as well. I'll support either of those, if you have a preference.

**Comment by ryelle** [comment] 2024-12-06 15:19
Yes, the links could be white since they're underlined, but personally I think a little color change (even this) is a nice accent. It looks like [blueberry-3 is already full-saturation](https://oklch.com/#86.82491843964975,0.06476298410191145,275.3672908860083,100), so I don't know that you'll be able to change it while keeping the same lightness. 

With a quick scan, blueberry-3 is used on borders, focus states, the "Draft" label on unpublished patterns, and as link color few places on https://wordpress.org/themes/ where, again, I thought we already did this - but this wasn't caught in QA 🙂

**Comment by bph** [comment] 2024-12-06 17:34
I agree `blueberry-3` is better for reading and works much better than the current darker blue.

**Comment by fcoveram** [comment] 2024-12-09 11:31
I think it's important to keep the blue hue as it's a brand trait that we've been applying in all the latest updates. Changing it to white will weaken the color application in dark contexts. But at the same time, I agree that its contrast over charcoal could be better.

I tried a new color with a lightness set between current `blueberry-2` and `blueberry-3`. The color meets contrast requirements and looks good better than `blueberry-2`.

Here is a screenshot from my browser's inspector. On the left the current site with `blueberry-2`, on the right the new color: `#9fb1ff`.

![Image](https://github.com/user-attachments/assets/7567d0cb-c533-46b9-a138-ed0db6b32473)

[Here](https://huetone.ardov.me/?palette=N4IgdghgtgpiBcIDqB7ATgEwAppgZzwAIwYB3QgYxQBt08QAaEACwFd8EBtUSWBEAEJoIYDIxBVaaevE4gAxAEYMAZgCsAIwAs4%2BQCZFKgGYYdTeSoAcayzACcugOwa7ABiNHdH75-MVHGIoeujAeesEAugC%2BDDzQcIhCIhgAtHriknRcCsrq2roGxqa6Vjb2Ti7uvgp2RhpB1fL%2BgcHmoUbhntERTAAuKCQycgAiEGgA1uLDMDAADuICAuLpTAByZOIq4jrRQA) you can see the color composition and how it works with the three darkest shades of charcoal. In the image below, the first row of colors is the current set, and second row has the new color (`#9fb1ff`)

<img src=https://github.com/user-attachments/assets/194c81f4-5923-4863-adca-cf9af4255d93 width=350>

---

If this idea sounds good, I envision two paths: update `blueberry-2` or add it as new. What do you think?

**Comment by ryelle** [comment] 2024-12-09 21:53
This works for me, the text is more visible 👍🏻 

> I envision two paths: update blueberry-2 or add it as new.

It works nicely that the colors are numbered in order of lightness, so I would rather not add a `blueberry-4` that's darker than `3`. The current `blueberry-2` always used against dark colors, so I don't see an issue with updating the color value itself.

**Comment by fcoveram** [comment] 2024-12-10 09:14
True. `blueberry-2` was thought for dark background contexts. Let's update it then. I will update the Figma's Design Library.

**Closed as completed** 2024-12-13 20:00 UTC
Labels: [Component] Theme, Accessibility
